### PR TITLE
Bump macOS deployment target to 12

### PR DESCRIPTION
**Pull request by calcmogul**

### CODE REVIEW

**Comment by ThadHouse** [comment]
Can you bump the version number in build.gradle to 2024.3.2

**Comment by calcmogul** [comment]
Note that macOS 11 security updates stopped September 26, 2023.

**Comment by sciencewhiz** [comment]
Does this only affect C++?

**Comment by calcmogul** [comment]
I think so.

**Review by PeterJohnson — APPROVED** [review]

**Pull request merged**
