### PR TITLE
Make deprecations produce errors in WPILib builds

### PR DESCRIPTION
**Pull request by calcmogul**

### CODE REVIEW

**Comment by PeterJohnson** [comment]
I thought we turned this off explicitly because in some cases there's no way to suppress the deprecation warning.

**Comment by calcmogul** [comment]
We've been using the WPI_IGNORE_DEPRECATED and WPI_UNIGNORE_DEPRECATED macros to suppress deprecated calls we have to make internally. allwpilib already removes the `-Wno-error=deprecated-declarations` flag, so this is just making that apply to everything that uses native-utils.

**Comment by PeterJohnson** [comment]
We remove it only for RoboRIO targets? https://github.com/wpilibsuite/allwpilib/blob/main/shared/config.gradle#L58-L63

**Comment by calcmogul** [comment]
I think that was an oversight by me. We build everything for athena, so it caught all the instances of unsuppressed deprecation warnings.

**Review by PeterJohnson — APPROVED** [review]

**Pull request merged**
