### PR TITLE
Allow C enums with fixed underlying type on macOS

### PR DESCRIPTION
**Pull request by auscompgeek**
For wpilibsuite/allwpilib#3297

### CODE REVIEW

**Comment by auscompgeek** [comment]
Hm, fun with newline endings...

**Comment by PeterJohnson** [comment]
Should this also be added to macCompilerArgs?

**Comment by ThadHouse** [comment]
I'd also add it to objc and objcpp for Mac too

**Comment by auscompgeek** [comment]
> Should this also be added to macCompilerArgs?

That's only for C++, right? This is already part of the C++ standard.

> I'd also add it to objc and objcpp for Mac too

Can add for objc.

**Comment by auscompgeek** [comment]
Wait, objc doesn't specify `-pedantic`, and this warning isn't in `-Wall -Wextra` either. Do we really need to specify it?

**Comment by PeterJohnson** [comment]
No, if pedantic isn't specified, it's not needed.

**Comment by auscompgeek** [comment]
This seems fine to me then. I tested this with the corresponding PR on my Mac and everything built successfully.

**Comment by PeterJohnson** [comment]
> That's only for C++, right? This is already part of the C++ standard.

The problem is C++ compilers sometimes warn on C things if they happen in an extern "C" block.  I'm not sure if clang does this...

**Comment by auscompgeek** [comment]
> The problem is C++ compilers sometimes warn on C things if they happen in an extern "C" block.

Quickly tested that, `clang++ -std=c++11 -pedantic` doesn't warn about enums with fixed underlying type in an `extern "C"` block.

**Review by ThadHouse — APPROVED** [review]

**Pull request merged**
